

############################################################
#  Install required packages 
############################################################

# Install SignalingProfiler
devtools::install_github('https://github.com/SaccoPerfettoLab/SignalingProfiler/')

# Install PatientProfiler
devtools::install_github('https://github.com/SaccoPerfettoLab/PatientProfiler/')




############################################################
# Load required libraries
############################################################

library(PatientProfiler)
library(SignalingProfiler)
library(tidyverse)


############################################################
# 2) Download and load example datasets
############################################################

# Load phosphoproteomics data
url <- "https://perfettolab.bio.uniroma1.it/PerfettoLabData/PatientProfiler/MOX_example/Brca_phospho.tsv"
file_path <- tempfile(fileext = ".tsv")
response <- httr::GET(url, httr::write_disk(file_path, overwrite = TRUE))
if (httr::http_status(response)$category == "Success") {
  phosphoproteomics_data <- utils::read.delim(file_path, sep = "\t", header = TRUE, stringsAsFactors = FALSE)
} else {
  stop("Error:", httr::http_status(response)$message)
}

# Load proteomics data
url <- "https://perfettolab.bio.uniroma1.it/PerfettoLabData/PatientProfiler/MOX_example/Brca_prot.tsv"
file_path <- tempfile(fileext = ".tsv")
response <- httr::GET(url, httr::write_disk(file_path, overwrite = TRUE))
if (httr::http_status(response)$category == "Success") {
  proteomics_data <- utils::read.delim(file_path, sep = "\t", header = TRUE, stringsAsFactors = FALSE)
} else {
  stop("Error:", httr::http_status(response)$message)
}

# Load trasncriptomics data
url <- "https://perfettolab.bio.uniroma1.it/PerfettoLabData/PatientProfiler/MOX_example/Brca_transc.tsv"
file_path <- tempfile(fileext = ".tsv")
response <- httr::GET(url, httr::write_disk(file_path, overwrite = TRUE))
if (httr::http_status(response)$category == "Success") {
  transcriptomics_data <- utils::read.delim(file_path, sep = "\t", header = TRUE, stringsAsFactors = FALSE)
} else {
  stop("Error:", httr::http_status(response)$message)
}


############################################################
# Step 1 of PatientProfiler R package : Preprocessing with omics_update()
############################################################

# The function omics_update() harmonizes and prepares the three omics
# datasets for downstream analysis. Specifically, it can:
# - Filter low-quality or poorly detected features
# - Handle missing values (imputation)
# - Aggregate redundant measurements (e.g., multiple peptides per protein)
# - Build sequence windows around phosphosites
# - Normalize and standardize data (z-score)
# - Save intermediate outputs for transparency and reproducibility


# For additional informations about this function, you can check the 
# PatientProfiler GitHub https://github.com/SaccoPerfettoLab/PatientProfiler

omics_update(
  df_tr = transcriptomics_data,   
  df_pr = proteomics_data,   
  df_ph = phosphoproteomics_data,  
  threshold = 80,
  m= 5,
  collapse = "median",
  sw_len = 7, 
  uniprot_idx = NULL,
  pep_col_name = "Peptide",
  imp_method = "norm",
  zscore = TRUE,   
  zmethod = "column",   
  metric = "median",
  output_dir = 'Mox_data'
)

# The updated datasets generated by this function should be used
# for downstream analyses, as they contain processed and harmonized data.


